class AppLocalizations {
  static const Map<String, Map<String, String>> translations = {
    'id': {
      // Navigation & Common
      'home': 'Beranda',
      'dashboard': 'Dashboard',
      'cart': 'Keranjang',
      'profile': 'Profil',
      'settings': 'Pengaturan',
      'logout': 'Keluar',
      'login': 'Masuk',
      'register': 'Daftar',
      'back': 'Kembali',
      'next': 'Selanjutnya',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'edit': 'Edit',
      'close': 'Tutup',
      'ok': 'OK',
      'yes': 'Ya',
      'no': 'Tidak',

      // Register Page
      'register_title': 'Daftar Akun belanja.in',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Konfirmasi Password',
      'register_button': 'Register',
      'already_have_account': 'Sudah punya akun?',
      'register_success': 'Registrasi berhasil! Silakan login.',
      'email_already_exists': 'Email sudah terdaftar. Silakan login.',
      'email_empty': 'Email tidak boleh kosong',
      'email_invalid': 'Masukkan email yang valid',
      'password_empty': 'Password tidak boleh kosong',
      'password_min': 'Password minimal 6 karakter',
      'confirm_password_empty': 'Konfirmasi password tidak boleh kosong',
      'password_mismatch': 'Password tidak cocok',

      // Login Page
      'login_title': 'Masuk ke belanja.in',
      'login_button': 'Masuk',
      'no_account': 'Belum punya akun?',
      'login_success': 'Login berhasil!',
      'login_failed': 'Email atau password salah',

      // Dashboard
      'welcome': 'Selamat datang',
      'products': 'Produk',
      'no_products': 'Tidak ada produk',
      'search': 'Cari produk...',

      // Cart
      'cart_empty': 'Keranjang kosong',
      'cart_total': 'Total',
      'checkout': 'Checkout',
      'add_to_cart': 'Tambah ke Keranjang',
      'remove_from_cart': 'Hapus dari Keranjang',
      'quantity': 'Jumlah',
      'price': 'Harga',

      // Profile
      'my_profile': 'Profil Saya',
      'edit_profile': 'Edit Profil',
      'change_password': 'Ubah Password',
      'name': 'Nama',
      'old_password': 'Password Lama',
      'new_password': 'Password Baru',
      'profile_updated': 'Profil berhasil diperbarui',

      // Settings
      'app_settings': 'Pengaturan Aplikasi',
      'language': 'Bahasa',
      'select_language': 'Pilih Bahasa',
      'notifications': 'Notifikasi',
      'enable_notifications': 'Aktifkan Notifikasi',
      'notifications_enabled': 'Notifikasi Diaktifkan 🔔',
      'notifications_disabled': 'Notifikasi Dimatikan 🔕',
      'device_info': 'Device Info',
      'view_device_info': 'Lihat detail perangkat kamu',
      'feedback': 'Feedback',
      'send_feedback': 'Berikan masukan untuk aplikasi ini',
      'about_app': 'Tentang Aplikasi',
      'app_info': 'Informasi versi & deskripsi aplikasi',
      'app_description': 'Belanja.in adalah platform e-commerce...',
      'theme': 'Tema',
      'light_theme': 'Terang',
      'dark_theme': 'Gelap',
      'theme_changed': 'Tema berhasil diubah',
      'language_changed': 'Bahasa berhasil diubah',

      // Payment
      'payment': 'Pembayaran',
      'payment_method': 'Metode Pembayaran',
      'pay_now': 'Bayar Sekarang',
      'payment_success': 'Pembayaran berhasil',
      'payment_failed': 'Pembayaran gagal',

      // Common Messages
      'loading': 'Memuat...',
      'error': 'Terjadi kesalahan',
      'success': 'Berhasil',
      'warning': 'Peringatan',
      'info': 'Informasi',
      'version': 'Versi',
      'all_rights_reserved': 'Semua hak dilindungi © 2025 Kelompok 3',
    },
    'en': {
      'home': 'Home',
      'dashboard': 'Dashboard',
      'cart': 'Cart',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      'login': 'Login',
      'register': 'Register',
      'back': 'Back',
      'next': 'Next',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',

      'register_title': 'Create Account on Belanja.in',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'register_button': 'Register',
      'already_have_account': 'Already have an account?',
      'register_success': 'Registration successful! Please login.',
      'email_already_exists': 'Email already registered. Please login.',
      'email_empty': 'Email cannot be empty',
      'email_invalid': 'Enter a valid email',
      'password_empty': 'Password cannot be empty',
      'password_min': 'Password must be at least 6 characters',
      'confirm_password_empty': 'Confirm password cannot be empty',
      'password_mismatch': 'Passwords do not match',

      'login_title': 'Login to Belanja.in',
      'login_button': 'Login',
      'no_account': 'Don\'t have an account?',
      'login_success': 'Login successful!',
      'login_failed': 'Email or password is incorrect',

      'welcome': 'Welcome',
      'products': 'Products',
      'no_products': 'No products available',
      'search': 'Search products...',

      'cart_empty': 'Cart is empty',
      'cart_total': 'Total',
      'checkout': 'Checkout',
      'add_to_cart': 'Add to Cart',
      'remove_from_cart': 'Remove from Cart',
      'quantity': 'Quantity',
      'price': 'Price',

      'my_profile': 'My Profile',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'name': 'Name',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'profile_updated': 'Profile updated successfully',

      'app_settings': 'App Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'notifications_enabled': 'Notifications Enabled 🔔',
      'notifications_disabled': 'Notifications Disabled 🔕',
      'device_info': 'Device Info',
      'view_device_info': 'View device details',
      'feedback': 'Feedback',
      'send_feedback': 'Send feedback for this app',
      'about_app': 'About App',
      'app_info': 'App version & description',
      'app_description': 'Belanja.in is an e-commerce platform...',
      'theme': 'Theme',
      'light_theme': 'Light',
      'dark_theme': 'Dark',
      'theme_changed': 'Theme changed successfully',
      'language_changed': 'Language changed successfully',

      'payment': 'Payment',
      'payment_method': 'Payment Method',
      'pay_now': 'Pay Now',
      'payment_success': 'Payment successful',
      'payment_failed': 'Payment failed',

      'loading': 'Loading...',
      'error': 'An error occurred',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Information',
      'version': 'Version',
      'all_rights_reserved': 'All rights reserved © 2025 Group 3',
    },
    'es': {
      'home': 'Inicio',
      'dashboard': 'Panel',
      'cart': 'Carrito',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'logout': 'Cerrar sesión',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'back': 'Atrás',
      'next': 'Siguiente',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'close': 'Cerrar',
      'ok': 'OK',
      'yes': 'Sí',
      'no': 'No',

      'register_title': 'Crear cuenta en belanja.in',
      'email': 'Correo',
      'password': 'Contraseña',
      'confirm_password': 'Confirmar Contraseña',
      'register_button': 'Registrarse',
      'already_have_account': '¿Ya tienes cuenta?',
      'register_success': '¡Registro exitoso! Por favor, inicia sesión.',
      'email_already_exists':
          'El correo ya está registrado. Por favor, inicia sesión.',
      'email_empty': 'El correo no puede estar vacío',
      'email_invalid': 'Ingresa un correo válido',
      'password_empty': 'La contraseña no puede estar vacía',
      'password_min': 'La contraseña debe tener al menos 6 caracteres',
      'confirm_password_empty': 'Confirmar contraseña no puede estar vacía',
      'password_mismatch': 'Las contraseñas no coinciden',

      'login_title': 'Iniciar sesión en belanja.in',
      'login_button': 'Iniciar sesión',
      'no_account': '¿No tienes cuenta?',
      'login_success': '¡Inicio de sesión exitoso!',
      'login_failed': 'Correo o contraseña incorrecto',

      'welcome': 'Bienvenido',
      'products': 'Productos',
      'no_products': 'Sin productos disponibles',
      'search': 'Buscar productos...',

      'cart_empty': 'El carrito está vacío',
      'cart_total': 'Total',
      'checkout': 'Pagar',
      'add_to_cart': 'Agregar al carrito',
      'remove_from_cart': 'Quitar del carrito',
      'quantity': 'Cantidad',
      'price': 'Precio',

      'my_profile': 'Mi Perfil',
      'edit_profile': 'Editar Perfil',
      'change_password': 'Cambiar Contraseña',
      'name': 'Nombre',
      'old_password': 'Contraseña Anterior',
      'new_password': 'Nueva Contraseña',
      'profile_updated': 'Perfil actualizado correctamente',

      'app_settings': 'Configuración de Aplicación',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'notifications': 'Notificaciones',
      'enable_notifications': 'Habilitar Notificaciones',
      'notifications_enabled': 'Notificaciones Habilitadas 🔔',
      'notifications_disabled': 'Notificaciones Deshabilitadas 🔕',
      'device_info': 'Información de dispositivo',
      'view_device_info': 'Ver detalles del dispositivo',
      'feedback': 'Comentarios',
      'send_feedback': 'Enviar comentarios sobre la aplicación',
      'about_app': 'Acerca de la Aplicación',
      'app_info': 'Versión e información de la aplicación',
      'app_description':
          'belanja.in es una plataforma de comercio electrónico...',
      'theme': 'Tema',
      'light_theme': 'Claro',
      'dark_theme': 'Oscuro',
      'theme_changed': 'Tema cambiado correctamente',
      'language_changed': 'Idioma cambiado correctamente',

      'payment': 'Pago',
      'payment_method': 'Método de pago',
      'pay_now': 'Pagar ahora',
      'payment_success': 'Pago exitoso',
      'payment_failed': 'Pago fallido',

      'loading': 'Cargando...',
      'error': 'Ocurrió un error',
      'success': 'Éxito',
      'warning': 'Advertencia',
      'info': 'Información',
      'version': 'Versión',
      'all_rights_reserved': 'Todos los derechos reservados © 2025 Grupo 3',
    },
    'fr': {
      'home': 'Accueil',
      'dashboard': 'Tableau de bord',
      'cart': 'Panier',
      'profile': 'Profil',
      'settings': 'Paramètres',
      'logout': 'Se déconnecter',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'back': 'Retour',
      'next': 'Suivant',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'close': 'Fermer',
      'ok': 'OK',
      'yes': 'Oui',
      'no': 'Non',

      'register_title': 'Créer un compte sur belanja.in',
      'email': 'Email',
      'password': 'Mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'register_button': 'S\'inscrire',
      'already_have_account': 'Avez-vous déjà un compte?',
      'register_success': 'Inscription réussie! Veuillez vous connecter.',
      'email_already_exists':
          'Cet email est déjà enregistré. Veuillez vous connecter.',
      'email_empty': 'L\'email ne peut pas être vide',
      'email_invalid': 'Entrez un email valide',
      'password_empty': 'Le mot de passe ne peut pas être vide',
      'password_min': 'Le mot de passe doit contenir au moins 6 caractères',
      'confirm_password_empty':
          'La confirmation du mot de passe ne peut pas être vide',
      'password_mismatch': 'Les mots de passe ne correspondent pas',

      'login_title': 'Connexion à belanja.in',
      'login_button': 'Se connecter',
      'no_account': 'Pas encore inscrit?',
      'login_success': 'Connexion réussie!',
      'login_failed': 'Email ou mot de passe incorrect',

      'welcome': 'Bienvenue',
      'products': 'Produits',
      'no_products': 'Aucun produit disponible',
      'search': 'Rechercher des produits...',

      'cart_empty': 'Le panier est vide',
      'cart_total': 'Total',
      'checkout': 'Passer la commande',
      'add_to_cart': 'Ajouter au panier',
      'remove_from_cart': 'Retirer du panier',
      'quantity': 'Quantité',
      'price': 'Prix',

      'my_profile': 'Mon Profil',
      'edit_profile': 'Modifier le profil',
      'change_password': 'Changer le mot de passe',
      'name': 'Nom',
      'old_password': 'Ancien mot de passe',
      'new_password': 'Nouveau mot de passe',
      'profile_updated': 'Profil mis à jour avec succès',

      'app_settings': 'Paramètres de l\'application',
      'language': 'Langue',
      'select_language': 'Sélectionner la langue',
      'notifications': 'Notifications',
      'enable_notifications': 'Activer les notifications',
      'notifications_enabled': 'Notifications Activées 🔔',
      'notifications_disabled': 'Notifications Désactivées 🔕',
      'device_info': 'Info dispositif',
      'view_device_info': 'Voir les détails du dispositif',
      'feedback': 'Commentaires',
      'send_feedback': 'Envoyer des commentaires sur l\'application',
      'about_app': 'À propos de l\'application',
      'app_info': 'Version et description de l\'application',
      'app_description':
          'belanja.in est une plateforme de commerce électronique...',
      'theme': 'Thème',
      'light_theme': 'Clair',
      'dark_theme': 'Sombre',
      'theme_changed': 'Thème changé avec succès',
      'language_changed': 'Langue changée avec succès',

      'payment': 'Paiement',
      'payment_method': 'Méthode de paiement',
      'pay_now': 'Payer maintenant',
      'payment_success': 'Paiement réussi',
      'payment_failed': 'Échec du paiement',

      'loading': 'Chargement...',
      'error': 'Une erreur est survenue',
      'success': 'Succès',
      'warning': 'Avertissement',
      'info': 'Information',
      'version': 'Version',
      'all_rights_reserved': 'Tous droits réservés © 2025 Groupe 3',
    },
    'de': {
      'home': 'Startseite',
      'dashboard': 'Übersicht',
      'cart': 'Warenkorb',
      'profile': 'Profil',
      'settings': 'Einstellungen',
      'logout': 'Abmelden',
      'login': 'Anmelden',
      'register': 'Registrieren',
      'back': 'Zurück',
      'next': 'Weiter',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'close': 'Schließen',
      'ok': 'OK',
      'yes': 'Ja',
      'no': 'Nein',

      'register_title': 'Konto auf belanja.in erstellen',
      'email': 'E-Mail',
      'password': 'Passwort',
      'confirm_password': 'Passwort bestätigen',
      'register_button': 'Registrieren',
      'already_have_account': 'Haben Sie bereits ein Konto?',
      'register_success':
          'Registrierung erfolgreich! Bitte melden Sie sich an.',
      'email_already_exists':
          'Diese E-Mail ist bereits registriert. Bitte melden Sie sich an.',
      'email_empty': 'E-Mail darf nicht leer sein',
      'email_invalid': 'Geben Sie eine gültige E-Mail ein',
      'password_empty': 'Passwort darf nicht leer sein',
      'password_min': 'Passwort muss mindestens 6 Zeichen lang sein',
      'confirm_password_empty': 'Passwortbestätigung darf nicht leer sein',
      'password_mismatch': 'Passwörter stimmen nicht überein',

      'login_title': 'Anmelden bei belanja.in',
      'login_button': 'Anmelden',
      'no_account': 'Haben Sie noch kein Konto?',
      'login_success': 'Anmeldung erfolgreich!',
      'login_failed': 'E-Mail oder Passwort ist falsch',

      'welcome': 'Willkommen',
      'products': 'Produkte',
      'no_products': 'Keine Produkte verfügbar',
      'search': 'Produkte suchen...',

      'cart_empty': 'Warenkorb ist leer',
      'cart_total': 'Gesamt',
      'checkout': 'Zur Kasse',
      'add_to_cart': 'In den Warenkorb',
      'remove_from_cart': 'Aus dem Warenkorb entfernen',
      'quantity': 'Menge',
      'price': 'Preis',

      'my_profile': 'Mein Profil',
      'edit_profile': 'Profil bearbeiten',
      'change_password': 'Passwort ändern',
      'name': 'Name',
      'old_password': 'Altes Passwort',
      'new_password': 'Neues Passwort',
      'profile_updated': 'Profil erfolgreich aktualisiert',

      'app_settings': 'App-Einstellungen',
      'language': 'Sprache',
      'select_language': 'Sprache wählen',
      'notifications': 'Benachrichtigungen',
      'enable_notifications': 'Benachrichtigungen aktivieren',
      'notifications_enabled': 'Benachrichtigungen aktiviert 🔔',
      'notifications_disabled': 'Benachrichtigungen deaktiviert 🔕',
      'device_info': 'Geräteinformationen',
      'view_device_info': 'Gerätedetails anzeigen',
      'feedback': 'Rückmeldung',
      'send_feedback': 'Feedback zur App geben',
      'about_app': 'Über die App',
      'app_info': 'App-Version und Beschreibung',
      'app_description': 'belanja.in ist eine E-Commerce-Plattform...',
      'theme': 'Design',
      'light_theme': 'Hell',
      'dark_theme': 'Dunkel',
      'theme_changed': 'Design erfolgreich geändert',
      'language_changed': 'Sprache erfolgreich geändert',

      'payment': 'Zahlung',
      'payment_method': 'Zahlungsweise',
      'pay_now': 'Jetzt zahlen',
      'payment_success': 'Zahlung erfolgreich',
      'payment_failed': 'Zahlung fehlgeschlagen',

      'loading': 'Wird geladen...',
      'error': 'Ein Fehler ist aufgetreten',
      'success': 'Erfolg',
      'warning': 'Warnung',
      'info': 'Information',
      'version': 'Version',
      'all_rights_reserved': 'Alle Rechte vorbehalten © 2025 Gruppe 3',
    },
    'ja': {
      'home': 'ホーム',
      'dashboard': 'ダッシュボード',
      'cart': 'カート',
      'profile': 'プロフィール',
      'settings': '設定',
      'logout': 'ログアウト',
      'login': 'ログイン',
      'register': '登録',
      'back': '戻る',
      'next': '次へ',
      'save': '保存',
      'cancel': 'キャンセル',
      'delete': '削除',
      'edit': '編集',
      'close': '閉じる',
      'ok': 'OK',
      'yes': 'はい',
      'no': 'いいえ',

      'register_title': 'belanja.inにアカウントを作成',
      'email': 'メール',
      'password': 'パスワード',
      'confirm_password': 'パスワードを確認',
      'register_button': '登録',
      'already_have_account': 'すでにアカウントを持っていますか?',
      'register_success': '登録成功！ログインしてください。',
      'email_already_exists': 'このメールは既に登録されています。ログインしてください。',
      'email_empty': 'メールは空にできません',
      'email_invalid': '有効なメールを入力してください',
      'password_empty': 'パスワードは空にできません',
      'password_min': 'パスワードは最低6文字である必要があります',
      'confirm_password_empty': 'パスワード確認は空にできません',
      'password_mismatch': 'パスワードが一致しません',

      'login_title': 'belanja.inにログイン',
      'login_button': 'ログイン',
      'no_account': 'まだアカウントを持っていませんか?',
      'login_success': 'ログイン成功！',
      'login_failed': 'メールまたはパスワードが間違っています',

      'welcome': 'ようこそ',
      'products': '商品',
      'no_products': '利用可能な商品がありません',
      'search': '商品を検索...',

      'cart_empty': 'カートが空です',
      'cart_total': '合計',
      'checkout': 'チェックアウト',
      'add_to_cart': 'カートに追加',
      'remove_from_cart': 'カートから削除',
      'quantity': '数量',
      'price': '価格',

      'my_profile': 'マイプロフィール',
      'edit_profile': 'プロフィールを編集',
      'change_password': 'パスワードを変更',
      'name': '名前',
      'old_password': '古いパスワード',
      'new_password': '新しいパスワード',
      'profile_updated': 'プロフィールが正常に更新されました',

      'app_settings': 'アプリ設定',
      'language': '言語',
      'select_language': '言語を選択',
      'notifications': '通知',
      'enable_notifications': '通知を有効にする',
      'notifications_enabled': '通知有効 🔔',
      'notifications_disabled': '通知無効 🔕',
      'device_info': 'デバイス情報',
      'view_device_info': 'デバイスの詳細を表示',
      'feedback': 'フィードバック',
      'send_feedback': 'アプリについてのフィードバックを送信',
      'about_app': 'アプリについて',
      'app_info': 'アプリバージョンと説明',
      'app_description': 'belanja.inはeコマースプラットフォームです...',
      'theme': 'テーマ',
      'light_theme': 'ライト',
      'dark_theme': 'ダーク',
      'theme_changed': 'テーマが正常に変更されました',
      'language_changed': '言語が正常に変更されました',

      'payment': '支払い',
      'payment_method': '支払方法',
      'pay_now': '今すぐ支払う',
      'payment_success': '支払い成功',
      'payment_failed': '支払い失敗',

      'loading': '読み込み中...',
      'error': 'エラーが発生しました',
      'success': '成功',
      'warning': '警告',
      'info': '情報',
      'version': 'バージョン',
      'all_rights_reserved': '© 2025 グループ3 著作権所有',
    },
    'zh': {
      'home': '首页',
      'dashboard': '仪表板',
      'cart': '购物车',
      'profile': '个人资料',
      'settings': '设置',
      'logout': '登出',
      'login': '登录',
      'register': '注册',
      'back': '返回',
      'next': '下一步',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'close': '关闭',
      'ok': '确定',
      'yes': '是',
      'no': '否',

      'register_title': '在belanja.in上创建账户',
      'email': '电子邮件',
      'password': '密码',
      'confirm_password': '确认密码',
      'register_button': '注册',
      'already_have_account': '已有账户?',
      'register_success': '注册成功！请登录。',
      'email_already_exists': '该电子邮件已被注册。请登录。',
      'email_empty': '电子邮件不能为空',
      'email_invalid': '请输入有效的电子邮件',
      'password_empty': '密码不能为空',
      'password_min': '密码至少需要6个字符',
      'confirm_password_empty': '确认密码不能为空',
      'password_mismatch': '密码不匹配',

      'login_title': '登录belanja.in',
      'login_button': '登录',
      'no_account': '没有账户?',
      'login_success': '登录成功！',
      'login_failed': '电子邮件或密码不正确',

      'welcome': '欢迎',
      'products': '产品',
      'no_products': '没有可用的产品',
      'search': '搜索产品...',

      'cart_empty': '购物车为空',
      'cart_total': '总计',
      'checkout': '结账',
      'add_to_cart': '加入购物车',
      'remove_from_cart': '从购物车中移除',
      'quantity': '数量',
      'price': '价格',

      'my_profile': '我的个人资料',
      'edit_profile': '编辑个人资料',
      'change_password': '更改密码',
      'name': '名称',
      'old_password': '旧密码',
      'new_password': '新密码',
      'profile_updated': '个人资料已成功更新',

      'app_settings': '应用设置',
      'language': '语言',
      'select_language': '选择语言',
      'notifications': '通知',
      'enable_notifications': '启用通知',
      'notifications_enabled': '通知已启用 🔔',
      'notifications_disabled': '通知已禁用 🔕',
      'device_info': '设备信息',
      'view_device_info': '查看设备详情',
      'feedback': '反馈',
      'send_feedback': '发送应用反馈',
      'about_app': '关于应用',
      'app_info': '应用版本和描述',
      'app_description': 'belanja.in是一个电子商务平台...',
      'theme': '主题',
      'light_theme': '浅色',
      'dark_theme': '深色',
      'theme_changed': '主题已成功更改',
      'language_changed': '语言已成功更改',

      'payment': '付款',
      'payment_method': '付款方式',
      'pay_now': '立即付款',
      'payment_success': '付款成功',
      'payment_failed': '付款失败',

      'loading': '正在加载...',
      'error': '发生错误',
      'success': '成功',
      'warning': '警告',
      'info': '信息',
      'version': '版本',
      'all_rights_reserved': '版权所有© 2025 第3组',
    },
  };

  /// Get translated string for current language
  static String t(String key, {String languageCode = 'id'}) {
    return translations[languageCode]?[key] ?? key;
  }

  /// Get all available languages
  static Map<String, Map<String, String>> getLanguages() {
    return {
      'id': {'name': 'Indonesia', 'flag': '🇮🇩'},
      'en': {'name': 'English', 'flag': '🇬🇧'},
      'es': {'name': 'Español', 'flag': '🇪🇸'},
      'fr': {'name': 'Français', 'flag': '🇫🇷'},
      'de': {'name': 'Deutsch', 'flag': '🇩🇪'},
      'ja': {'name': '日本語', 'flag': '🇯🇵'},
      'zh': {'name': '中文', 'flag': '🇨🇳'},
    };
  }
}
